### ISSUE TITLE
TypeError if a GeometryCollection is passed

### ISSUE THREAD

**Issue by simonepri** [pelias/polygon-lookup#28]
If this is passed to the constructor, the package throws an error:
`{ type: 'GeometryCollection', geometries: [ { type: 'MultiPolygon', coordinates: [Array] } ] }`

```
TypeError: Cannot read property 'forEach' of undefined
    at PolygonLookup.loadFeatureCollection (./is-land/node_modules/polygon-lookup/index.js:169:22)
    at new PolygonLookup (./is-land/node_modules/polygon-lookup/index.js:23:10)
    at isLand (./is-land/index.js:20:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
```

**Comment by missinglink** [comment]
hi @simonepri, the library currently only supports `FeatureCollections` not `GeometryCollections` but we would be happy to review a PR to add this functionality.

**Comment by simonepri** [comment]
This should be enough:
```
function geometryCollection2featureCollection(geojson) {
  const feats = geojson.geometries.map(geom => {
    return {
      type: 'Feature',
      geometry: geom
    };
  });
  return {type: 'FeatureCollection', features: feats};
}
```
I'll open a PR soon

**Comment by simonepri** [comment]
Hi @missinglink,
since I found difficult to improve this package without change everything I've decided to build a new package from scratch that supports more types of lookups.

You can find it here:
https://github.com/simonepri/geojson-geometries-lookup

I think we can close this issue.
